const $ = (s) => document.querySelector(s);
const content = $('#content');
const modal = $('#modal');
let token = localStorage.getItem('platform_token');
let tenants = [], plans = [], invoices = [];
const titles = {dashboard:'Visão geral',tenants:'Transportadoras',plans:'Planos e limites',billing:'Financeiro',storage:'Armazenamento',support:'Suporte',announcements:'Comunicados',health:'Saúde do sistema',audit:'Auditoria'};
const money = (v) => Number(v || 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const number = (v) => Number(v || 0).toLocaleString('pt-BR');
const date = (v) => v ? new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}) : '—';
const esc = (v) => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge = (v) => `<span class="badge ${esc(v)}">${esc(v)}</span>`;
function toast(msg){const el=$('#alert');el.textContent=msg;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),3500)}
async function api(path,options={}){const r=await fetch('/api/platform'+path,{...options,headers:{'content-type':'application/json',authorization:`Bearer ${token}`,...options.headers}});if(r.status===401||r.status===403){logout();throw new Error('Acesso global não autorizado.')}const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Não foi possível concluir.');return body}
async function login(email,password){const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:email.trim().toLowerCase(),password})});const b=await r.json();if(!r.ok)throw new Error(b.error||'E-mail ou senha inválidos.');token=b.token;await api('/me');localStorage.setItem('platform_token',token);return b}
function logout(){token=null;localStorage.removeItem('platform_token');$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}
function showModal(html){$('#modalContent').innerHTML=`<div class="dialog-body">${html}</div>`;modal.showModal()}
function closeModal(){modal.close()}
modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}" class="empty">Nenhum registro encontrado.</td></tr>`}</tbody></table></div>`}

async function dashboard(){const d=await api('/dashboard');content.innerHTML=`
  <div class="hero"><div><h2>Operação da plataforma em tempo real</h2><p>${d.tenants.active} transportadoras ativas e ${d.trips.active} viagens acontecendo agora.</p></div><strong>${new Date().toLocaleDateString('pt-BR')}</strong></div>
  <div class="grid metrics">
    <div class="metric"><span>RECEITA DO MÊS</span><strong>${money(d.finance.revenue_month)}</strong><small>MRR previsto ${money(d.finance.mrr)}</small></div>
    <div class="metric"><span>TRANSPORTADORAS</span><strong>${number(d.tenants.total)}</strong><small>${d.tenants.new_this_month} novas neste mês</small></div>
    <div class="metric"><span>ALUNOS PROTEGIDOS</span><strong>${number(d.people.students)}</strong><small>${number(d.people.guardians)} responsáveis</small></div>
    <div class="metric"><span>A RECEBER</span><strong>${money(d.finance.receivable)}</strong><small>${d.finance.overdue_count} faturas vencidas</small></div>
  </div>
  <div class="grid two section-head"><div></div></div><div class="grid two">
   <div class="card"><h3>Ecossistema VaiEscolar</h3>${[['Equipe cadastrada',d.people.staff],['Veículos',d.people.vehicles],['Escolas',d.people.schools],['Viagens neste mês',d.trips.trips_month]].map(x=>`<div class="status-dot"><i></i><span>${x[0]}</span><strong style="margin-left:auto">${number(x[1])}</strong></div>`).join('')}</div>
   <div class="card"><h3>Pontos de atenção</h3>${[['Clientes em atenção',d.tenants.attention],['Chamados críticos',d.alerts.critical_tickets],['Chamados abertos',d.alerts.open_tickets],['Armazenamento rastreado',(Number(d.storage.bytes)/1048576).toFixed(1)+' MB']].map(x=>`<div class="status-dot"><i></i><span>${x[0]}</span><strong style="margin-left:auto">${x[1]}</strong></div>`).join('')}</div>
  </div>`}

async function loadTenants(){tenants=await api('/tenants');return tenants}
async function tenantView(){await Promise.all([loadTenants(),loadPlans()]);content.innerHTML=`<div class="section-head"><h2>Clientes da plataforma</h2><div class="toolbar"><input id="tenantSearch" placeholder="Buscar transportadora"><select id="tenantStatus"><option value="">Todos os status</option><option>active</option><option>trial</option><option>past_due</option><option>suspended</option><option>cancelled</option></select></div></div><div id="tenantTable"></div>`;renderTenants(tenants);$('#tenantSearch').oninput=filterTenants;$('#tenantStatus').onchange=filterTenants}
function filterTenants(){const q=$('#tenantSearch').value.toLowerCase(),s=$('#tenantStatus').value;renderTenants(tenants.filter(t=>(!q||(t.name+' '+(t.legal_email||'')).toLowerCase().includes(q))&&(!s||t.status===s)))}
function renderTenants(items){$('#tenantTable').innerHTML=table(['Transportadora','Plano','Uso','Assinatura','Criada em',''],items.map(t=>`<tr><td><strong>${esc(t.name)}</strong><br><small>${esc(t.legal_email||'sem e-mail comercial')}</small></td><td>${esc(t.plan_name||t.plan)}</td><td>${t.students} alunos · ${t.vehicles} veículos<br><small>${(Number(t.storage_bytes)/1048576).toFixed(1)} de ${t.storage_limit_mb||0} MB</small></td><td>${badge(t.status)}</td><td>${date(t.created_at)}</td><td class="actions"><button onclick="openTenant('${t.id}')">Gerenciar</button></td></tr>`).join(''))}
async function openTenant(id){const t=await api('/tenants/'+id);showModal(`<h2>${esc(t.name)}</h2><p class="muted">${t.counts.students} alunos · ${t.counts.users} usuários · ${t.counts.trips} viagens</p><form id="tenantForm" class="form-grid"><label>Nome<input name="name" value="${esc(t.name)}" required></label><label>Status<select name="status">${['trial','active','past_due','suspended','cancelled'].map(x=>`<option ${t.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label>E-mail comercial<input name="legal_email" value="${esc(t.legal_email||'')}"></label><label>Telefone<input name="legal_phone" value="${esc(t.legal_phone||'')}"></label><label>Plano<select name="plan_id">${plans.map(p=>`<option value="${p.id}" ${t.plan_id===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label>Ciclo<select name="billing_cycle"><option value="monthly">Mensal</option><option value="annual" ${t.billing_cycle==='annual'?'selected':''}>Anual</option></select></label><div class="full actions"><button class="primary" type="submit">Salvar alterações</button></div></form>`);$('#tenantForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));await api('/tenants/'+id,{method:'PUT',body:JSON.stringify(f)});await api('/tenants/'+id+'/subscription',{method:'PUT',body:JSON.stringify({plan_id:f.plan_id,billing_cycle:f.billing_cycle,status:f.status==='suspended'?'paused':f.status})});closeModal();toast('Transportadora atualizada.');tenantView()}}

async function loadPlans(){plans=await api('/plans');return plans}
async function plansView(){await loadPlans();content.innerHTML=`<div class="section-head"><h2>Planos, recursos e limites</h2><button class="secondary" onclick="planForm()">Novo plano</button></div>${table(['Plano','Preço mensal','Alunos','Equipe','Veículos','Armazenamento','Clientes',''],plans.map(p=>`<tr><td><strong>${esc(p.name)}</strong><br><small>${esc(p.code)}</small></td><td>${money(p.monthly_price)}</td><td>${p.max_students}</td><td>${p.max_staff}</td><td>${p.max_vehicles}</td><td>${p.storage_limit_mb} MB</td><td>${p.subscribers}</td><td class="actions"><button onclick="planFormById('${p.id}')">Editar</button></td></tr>`).join(''))}`}
function planFormById(id){planForm(plans.find(plan=>plan.id===id)||{})}
function planForm(p={}){showModal(`<h2>${p.id?'Editar':'Novo'} plano</h2><form id="planForm" class="form-grid"><label>Código<input name="code" value="${esc(p.code||'')}" ${p.id?'disabled':''} required></label><label>Nome<input name="name" value="${esc(p.name||'')}" required></label><label>Mensalidade<input name="monthly_price" type="number" step=".01" value="${p.monthly_price||0}"></label><label>Valor anual<input name="annual_price" type="number" step=".01" value="${p.annual_price||0}"></label>${[['max_students','Alunos',p.max_students||30],['max_staff','Equipe',p.max_staff||3],['max_vehicles','Veículos',p.max_vehicles||2],['max_schools','Escolas',p.max_schools||3],['storage_limit_mb','Armazenamento (MB)',p.storage_limit_mb||1024],['history_months','Histórico (meses)',p.history_months||12]].map(x=>`<label>${x[1]}<input name="${x[0]}" type="number" value="${x[2]}"></label>`).join('')}<label class="full">Recursos em JSON<textarea name="features">${esc(JSON.stringify(p.features||{gps:true,contracts:true},null,2))}</textarea></label><button class="primary full">Salvar plano</button></form>`);$('#planForm').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.target));['monthly_price','annual_price','max_students','max_staff','max_vehicles','max_schools','storage_limit_mb','history_months'].forEach(k=>b[k]=Number(b[k]));try{b.features=JSON.parse(b.features)}catch{return toast('JSON de recursos inválido.')}await api(p.id?'/plans/'+p.id:'/plans',{method:p.id?'PUT':'POST',body:JSON.stringify(b)});closeModal();toast('Plano salvo.');plansView()}}

async function billing(){const [rows]=await Promise.all([api('/invoices'),loadTenants()]);invoices=rows;content.innerHTML=`<div class="section-head"><h2>Receita e cobranças</h2><button class="secondary" onclick="invoiceForm()">Gerar cobrança</button></div>${table(['Cliente','Descrição','Valor','Vencimento','Status','Link',''],rows.map(i=>`<tr><td>${esc(i.tenant_name)}</td><td>${esc(i.description)}</td><td><strong>${money(i.amount)}</strong></td><td>${date(i.due_at)}</td><td>${badge(i.status)}</td><td><button onclick="copyInvoiceLink('${i.id}')">Copiar link</button></td><td class="actions">${i.status!=='paid'?`<button onclick="invoiceStatus('${i.id}','paid')">Confirmar</button>`:''}</td></tr>`).join(''))}`}
function copyInvoiceLink(id){const item=invoices.find(invoice=>invoice.id===id);if(item)copyLink(item.payment_url)}
function invoiceForm(){showModal(`<h2>Gerar cobrança</h2><form id="invoiceForm"><label>Transportadora<select name="tenant_id">${tenants.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></label><div class="form-grid"><label>Valor<input name="amount" type="number" step=".01" required></label><label>Vencimento<input name="due_at" type="date" required></label></div><label>Descrição<input name="description" value="Assinatura VaiEscolar"></label><label>Link externo do provedor (opcional)<input name="payment_url" placeholder="PIX, boleto ou cartão"></label><button class="primary">Criar e copiar link</button></form>`);$('#invoiceForm').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.target));b.amount=Number(b.amount);const i=await api('/invoices',{method:'POST',body:JSON.stringify(b)});await navigator.clipboard?.writeText(i.payment_url);closeModal();toast('Cobrança criada e link copiado.');billing()}}
async function invoiceStatus(id,status){await api('/invoices/'+id+'/status',{method:'POST',body:JSON.stringify({status})});toast('Fatura atualizada.');billing()}
function copyLink(v){navigator.clipboard?.writeText(v);toast('Link copiado.')}

async function storage(){const rows=await api('/storage');content.innerHTML=`<div class="section-head"><div><h2>Armazenamento por transportadora</h2><p class="muted">Objetos privados catalogados e limites do plano.</p></div></div>${table(['Transportadora','Utilizado','Limite','Ocupação','Objetos'],rows.map(r=>{const mb=Number(r.used_bytes)/1048576,pct=Math.min(100,mb/Number(r.storage_limit_mb||1)*100);return `<tr><td><strong>${esc(r.name)}</strong></td><td>${mb.toFixed(2)} MB</td><td>${r.storage_limit_mb||0} MB</td><td><div class="bar"><i style="width:${pct}%"></i></div><small>${pct.toFixed(1)}%</small></td><td>${r.objects}</td></tr>`}).join(''))}`}

async function support(){const [rows]=await Promise.all([api('/support'),loadTenants()]);content.innerHTML=`<div class="section-head"><h2>Central de suporte</h2><button class="secondary" onclick="ticketForm()">Abrir chamado</button></div>${table(['Prioridade','Cliente','Assunto','Status','Aberto em',''],rows.map(t=>`<tr><td>${badge(t.priority)}</td><td>${esc(t.tenant_name||'Plataforma')}</td><td><strong>${esc(t.subject)}</strong><br><small>${esc(t.description)}</small></td><td>${badge(t.status)}</td><td>${date(t.created_at)}</td><td class="actions"><button onclick="ticketUpdate('${t.id}','resolved')">Resolver</button></td></tr>`).join(''))}`}
function ticketForm(){showModal(`<h2>Novo chamado</h2><form id="ticketForm"><label>Transportadora<select name="tenant_id"><option value="">Plataforma</option>${tenants.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></label><label>Assunto<input name="subject" required></label><label>Descrição<textarea name="description" required></textarea></label><label>Prioridade<select name="priority"><option>normal</option><option>low</option><option>high</option><option>critical</option></select></label><button class="primary">Abrir chamado</button></form>`);$('#ticketForm').onsubmit=async e=>{e.preventDefault();await api('/support',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});closeModal();toast('Chamado aberto.');support()}}
async function ticketUpdate(id,status){await api('/support/'+id,{method:'PUT',body:JSON.stringify({status,priority:'normal'})});toast('Chamado atualizado.');support()}

async function announcements(){const rows=await api('/announcements');content.innerHTML=`<div class="section-head"><h2>Comunicação global</h2><button class="secondary" onclick="announcementForm()">Novo comunicado</button></div>${table(['Título','Público','Status','Envio'],rows.map(a=>`<tr><td><strong>${esc(a.title)}</strong><br><small>${esc(a.message)}</small></td><td>${esc(JSON.stringify(a.audience))}</td><td>${badge(a.status)}</td><td>${date(a.sent_at||a.scheduled_at)}</td></tr>`).join(''))}`}
function announcementForm(){showModal(`<h2>Novo comunicado</h2><form id="announcementForm"><label>Título<input name="title" required></label><label>Mensagem<textarea name="message" required></textarea></label><label>Público<select name="tenant_status"><option value="">Todas as transportadoras</option><option value="active">Somente ativas</option><option value="trial">Em teste</option><option value="past_due">Inadimplentes</option></select></label><label><input name="send_now" type="checkbox" style="width:auto"> Enviar agora por notificação</label><button class="primary">Salvar comunicado</button></form>`);$('#announcementForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await api('/announcements',{method:'POST',body:JSON.stringify({title:f.get('title'),message:f.get('message'),audience:{tenant_status:f.get('tenant_status')||null},send_now:f.get('send_now')==='on'})});closeModal();toast('Comunicado registrado.');announcements()}}

async function health(){const h=await api('/health');content.innerHTML=`<div class="section-head"><h2>Saúde dos serviços</h2><button class="secondary" onclick="health()">Atualizar</button></div><div class="grid metrics"><div class="metric"><span>VIAGENS ATIVAS</span><strong>${number(h.capacity.active_trips)}</strong><small>rastreamento simultâneo</small></div><div class="metric"><span>GPS EM 24 HORAS</span><strong>${number(h.capacity.gps_points_24h)}</strong><small>posições armazenadas</small></div><div class="metric"><span>WEBSOCKETS</span><strong>${number(h.websocket.connections)}</strong><small>${h.websocket.rooms} salas ativas</small></div><div class="metric"><span>POOL DO BANCO</span><strong>${h.databasePool.total}/${h.databasePool.max}</strong><small>${h.databasePool.waiting} aguardando</small></div></div><div class="grid two" style="margin-top:16px"><div class="card"><h3>Serviços principais</h3>${[['API',h.api],['Banco de dados',h.database],['Notificações',h.pushNotifications],['Cobranças',h.billingProvider]].map(x=>`<div class="status-dot"><i></i><span>${x[0]}</span><strong style="margin-left:auto">${x[1]}</strong></div>`).join('')}</div><div class="card"><h3>Diagnóstico</h3><p>Tempo do banco: <strong>${h.responseMs} ms</strong></p><p>Usuários ativos em 24h: <strong>${number(h.capacity.active_users_24h)}</strong></p><p>Node.js: <strong>${esc(h.node)}</strong></p><p>Verificado em: <strong>${date(h.checkedAt)}</strong></p><p class="muted">As integrações externas aparecem como configuradas somente quando suas credenciais estão presentes no servidor.</p></div></div><div class="card" style="margin-top:16px"><h3>Manutenções automáticas</h3>${h.maintenance.length?h.maintenance.map(m=>`<div class="status-dot"><i></i><span>${esc(m.job_name)} · ${date(m.created_at)}</span><strong style="margin-left:auto">${esc(m.status)} · ${number(m.affected_rows)} registros</strong></div>`).join(''):'<p class="muted">A primeira limpeza será executada após o servidor iniciar.</p>'}</div>`}
async function auditView(){const rows=await api('/audit');content.innerHTML=`<div class="section-head"><div><h2>Auditoria global</h2><p class="muted">Registro permanente das ações de alto privilégio.</p></div></div>${table(['Data','Responsável','Ação','Entidade','Transportadora','Origem'],rows.map(a=>`<tr><td>${date(a.created_at)}</td><td>${esc(a.actor_name||'sistema')}</td><td><strong>${esc(a.action)}</strong></td><td>${esc(a.entity_type)} ${esc(a.entity_id||'')}</td><td>${esc(a.tenant_name||'—')}</td><td>${esc(a.ip||'—')}</td></tr>`).join(''))}`}

const views={dashboard,tenants:tenantView,plans:plansView,billing,storage,support,announcements,health,audit:auditView};
async function navigate(view){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#pageTitle').textContent=titles[view];content.innerHTML='<div class="loader"></div>';try{await views[view]()}catch(e){content.innerHTML=`<div class="empty"><h3>Não foi possível carregar</h3><p>${esc(e.message)}</p></div>`}history.replaceState(null,'','#'+view);document.querySelector('aside').classList.remove('open')}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$('#menu').onclick=()=>document.querySelector('aside').classList.toggle('open');$('#logout').onclick=logout;
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{await login($('#email').value,$('#password').value);await start()}catch(err){$('#loginError').textContent=err.message}};
async function start(){try{const me=await api('/me');$('#userName').textContent=me.name;$('#login').classList.add('hidden');$('#app').classList.remove('hidden');navigate(location.hash.slice(1) in views?location.hash.slice(1):'dashboard')}catch{logout()}}
if(token)start();
